apiVersion: 1

deleteDatasources:
  - name: CMM
    orgId: 1

datasources:
- name: CMM
  type: crate-datasource
  access: proxy
  orgId: 1
  url: http://crate:4200
  version: 1
  jsonData:
    schema: mtt_measurement
    table: etmeasurementresult
    timeColumn: time_index
