version: "3.3"

services:
    mongo:
        command: --nojournal
        image: mongo:3.4
        logging:
            options:
                max-size: 1m
        networks:
            - showcase
        restart: unless-stopped
        volumes:
            - /home/ubuntu/showcase/mongo/:/data/db/

    orion-shopfloor:
        command: -dbhost mongo -db shopfloor -logLevel INFO
        depends_on:
            - mongo
        image: fiware/orion:2.2.0
        logging:
            options:
                max-size: 1m
        networks:
            - showcase
        restart: unless-stopped
        ports:
            - '1026:1026'

    orion-innovalia:
        command: -dbhost mongo -db innovalia -logLevel INFO
        depends_on:
            - mongo
        image: fiware/orion:2.2.0
        logging:
            options:
                max-size: 1m
        networks:
            - showcase
        restart: unless-stopped

    orion-gf:
        command: -dbhost mongo -db gf -logLevel INFO
        depends_on:
            - mongo
        image: fiware/orion:2.2.0
        logging:
            options:
                max-size: 1m
        networks:
            - showcase
        restart: unless-stopped

    quantumleap:
        depends_on:
            - orion-shopfloor
            - crate
        environment:
            - CRATE_HOST=http://crate
        image: smartsdk/quantumleap:0.6
        logging:
            options:
                max-size: 1m
        networks:
            - showcase
        restart: unless-stopped

    grafana:
        depends_on:
            - crate
        environment:
            - GF_INSTALL_PLUGINS=https://github.com/raintank/crate-datasource/archive/master.zip;crate-datasource
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_SERVER_DOMAIN=zerod.lab.fiware.org
            - GF_SERVER_ROOT_URL=https://zerod.lab.fiware.org
            - GF_SERVER_ROUTER_LOGGING=false
            - GF_DATABASE_PATH=grafana.db
            - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_password
        image: grafana/grafana:6.0.0
        logging:
            options:
                max-size: 1m
        networks:
            - showcase
        restart: unless-stopped
        secrets:
          - grafana_admin_password
        volumes:
            - /home/ubuntu/showcase/grafana/:/var/lib/grafana/
            - /home/ubuntu/showcase/static/grafana/datasources/:/etc/grafana/provisioning/datasources/
            - /home/ubuntu/showcase/static/grafana/dashboards/:/etc/grafana/provisioning/dashboards/

    crate:
        command: -Ccluster.name=zerod -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*"
        image: crate:3.1.6
        logging:
            options:
                max-size: 1m
        networks:
            - showcase
        ports:
            - '4200:4200'
        restart: unless-stopped
        volumes:
            - /home/ubuntu/showcase/crate/:/data/

    stream-mm-agent:
        depends_on:
            - mongo
            - stream-mm-server
        image: rdlabengpa/opcuaage:1.4.b
        logging:
            options:
                max-size: 1m
        networks:
            - showcase
        restart: unless-stopped
        volumes:
            - /home/ubuntu/showcase/static/mm/config.properties:/opt/iotagent-opcua/conf/config.properties

    stream-mm-server:
        depends_on:
            - orion-shopfloor
        image: rdlabengpa/opcuasrv:latest
        logging:
            options:
                max-size: 1m
        networks:
            - showcase
        restart: unless-stopped
        volumes:
            - /home/ubuntu/showcase/static/mm/config.js:/opt/boost-opcua-server/conf/config.js

    stream-cm:
        command: -cb http://orion-shopfloor:1026 -fs t_measurement -to 60
        depends_on:
            - orion-shopfloor
        image: repo.lab.fiware.org/stream-machine-coordinatemeasuring
        logging:
            options:
                max-size: 1m
        networks:
            - showcase
        restart: unless-stopped

    nginx:
        depends_on:
            - grafana
        image: repo.lab.fiware.org/nginx
        networks:
            -  showcase
        ports:
            - 80:80
            - 443:443
        restart: unless-stopped
        volumes:
            - /home/ubuntu/showcase/static/nginx.conf:/etc/nginx/nginx.conf

#   shopfloor, gf, innovalia
#    *-pep:
#        container_name: *-pep
#        depends_on:
#            - *-orion
#        image: fiware/pep-proxy:7.0.2
#        volumes:
#            - /opt/static/pep-*.js:/opt/fiware-pep-proxy/config.js
#        logging:
#            options:
#                max-size: 1m
#        networks:
#            nginx:
#                aliases:
#                    - *-pep


#   innovalia, gf
#    *-mysql:
#        image: mysql:8.0.12
#        environment:
#            - MYSQL_ROOT_PASSWORD=23sdfBJE33sf2
#            - MYSQL_ROOT_HOST=%
#        volumes:
#            - /storage/*-mysql:/var/lib/mysql
#        container_name: *-mysql
#        logging:
#            options:
#                max-size: 1m
#        networks: nginx
#        restart: unless-stopped

#   innovalia, gf
#    *-cynus:
#        dgepends_on:
#            - innovalia-orion
#            - innovalia-mysql
#        image: fiware/cygnus-ngsi:1.9.0
#        logging:
#            options:
#                max-size: 1m
#        networks: nginx
#        restart: unless-stopped
#        volumes:
#            - /opt/static/cygnus-*.conf:/opt/apache-flume/conf/agent.conf

secrets:
  grafana_admin_password:
    external: true

networks:
  showcase:
    external: true
